adminUser:
  password: vault:pr-359-23arc/adminUser:password
  username: admin
dashboardAuthID: vault:pr-359-23arc:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:pr-359-23arc:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-359-23arc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-359-23arc/prow:hmacToken
